### ISSUE TITLE
Item 2 fishery filtering

### ISSUE THREAD

**Issue by Killa-Be** [commfish/adfg_crab_observer#2]
Bering Sea Tanner was coded as EI in 91 and 92 and encompasses the entire EBS. In addition, Bering Sea Tanner was coded as QT in 93 and 94, but included fishing in the eastern area. I suggest that we filter the Tanner fishery to include the “EI” fisheries (91 and 92) and “QT” fisheries, but filter by statarea <660000.

**Comment by tymjackson** [comment]
Should be updated. I applied the same treatment to item 6 as well.
